// example/demo/fragment-vue-master/src/pages/Index/index.vue
<template>
  <div class="p-index-container">
    <div>This is fragment-vue-master</div>
    <div @click="push">切换 master hello</div>
    <div @click="push2">切换 master world</div>
    <div @click="push3">切换 子 application</div>
    <div @click="push4">切换 第2层的 grandson</div>
    <div @click="push5">切换 react</div>

    <div>==============================================</div>
    <div
      ref="other2"
      id="other2"
      style="background:#ccc;border:1px solid;"
    ></div>
    <div>--------------------------------------------------</div>
    <div
      ref="other3"
      id="other3"
      style="background:#666;border:1px solid;"
    ></div>
    <div>--------------------------------------------------</div>
    <div
      ref="other4"
      id="other3"
      style="background:#f90;border:1px solid;"
    ></div>
  </div>
</template>

<script>
import { appPool } from "../../global";

export default {
  name: "Index",
  data() {
    return {
      name: appPool.classNamespace
    };
  },
  methods: {
    push() {
      this.$router.push({
        name: "hello",
        params: { userId: "123" }
      });
    },
    push2() {
      this.$router.push({
        path: "/world",
        query: { plan: "private" }
      });
    },
    push3() {
      this.$router.push("/other2/hello");
    },
    push4() {
      // this.$router.push('/other3/hello')
      this.$router.push("/grandson/hello");
    },
    push5() {
      // this.$router.push('/other3/hello')
      this.$router.push("/reactfather");
    }
  },
  mounted() {
    const appinfo = [
      {
        name: "a45",
        applicationName: "reactfather",
        entry: "http://localhost:5020/app",
        contain: this.$refs.other3,
        baseUrl: "/reactfather",
        canActive() {
          // path
          // baseUrl 会被chapxi重写成包含父路径
          // 所以这里可以直接使用
          return location.pathname.startsWith(this.baseUrl);
        }
      }
      // {
      //   name: "a2",
      //   applicationName: "child",
      //   entry: "http://localhost:8082/app",
      //   contain: this.$refs.other3,
      //   baseUrl: "/other3",
      //   canActive() {
      //     return location.pathname.startsWith("/other3");
      //   }
      // }
    ];
    appPool.registerApps(appinfo);
  }
};
</script>

<style></style>

// example/demo/fragment-react-father/src/components/Index/index.js
import React from "react";
import { appPool } from "../../global";
import { globalEvent } from "jigsaw-mf";
import "./index.scss";

export default class Home extends React.Component {
  componentDidMount() {
    const _self = this;
    const appinfo = [
      {
        name: "a49",
        applicationName: "reactproduct",
        entry: "http://localhost:9200/app",
        contain: this.refs.container1,
        baseUrl: "/",
        canActive(baseUrl) {
          return window.location.pathname.startsWith(baseUrl);
        }
      },
      {
        name: "a50",
        applicationName: "reactnews",
        entry: "http://localhost:9300/app",
        contain: this.refs.container2,
        baseUrl: "/",
        canActive(baseUrl) {
          return window.location.pathname.startsWith(baseUrl);
        }
      }
      // {
      //     name: "a44",
      //     applicationName: "finder",
      //     entry: "http://localhost:9091/app",
      //     contain: this.refs.container3,
      //     baseUrl: "/",
      //     canActive(path) {
      //         return window.location.pathname.startsWith(this.baseUrl);
      //     }
      // },
      //   {
      //       name: "a45",
      //       applicationName: "reactfather",
      //       entry: "http://localhost:5020/app",
      //       contain: this.refs.container4,
      //       baseUrl: "/reactfather",
      //       canActive(path) {
      //
      //         // baseUrl 会被chapxi重写成包含父路径
      //         // 所以这里可以直接使用
      //         return window.location.pathname.startsWith(this.baseUrl);
      //       }
      //   }
    ];
    appPool.registerApps(appinfo);

    var evtSource = new EventSource("http://localhost:5020/event");
    evtSource.onmessage = function(e) {
      console.log("onmsg: " + e.data);
    };
    evtSource.onerror = function(e) {
      console.log("error", e);
      evtSource.close();

      const app = [
        {
          name: "a44",
          applicationName: "finder",
          entry: "http://localhost:9091/app",
          contain: _self.refs.container3,
          baseUrl: "/",
          canActive(path) {
            return window.location.pathname.startsWith(this.baseUrl);
          }
        }
      ];
      appPool.registerApps(app);
    };
  }

  render() {
    return (
      <React.Fragment>
        <div id="33" ref="container3"></div>
        <div id="11" ref="container1"></div>
        <div id="22" ref="container2"></div>
        <div id="44" ref="container4"></div>
      </React.Fragment>
    );
  }
}
